In [1]:
import os, sys
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist

In [2]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

print(x_train.shape)
print(t_train.shape)

(60000, 784)
(60000, 10)


In [4]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
print(batch_mask)

[17266 35388 46510 30672 32252 58204 48350  4479  5192  7603]


In [5]:
x_batch = x_train[batch_mask]

In [6]:
t_batch = t_train[batch_mask]

In [12]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.shape(1, t.size)
        y = y.shape(1, y.size)
        
    batch_size = y.shape[0]

    return -np.sum(t*np.log(y+1e-7)) / batch_size

In [13]:
def cross_entropy_error_numberlabel(y, t):
    if y.ndim == 1:
        t = t.shape(1, t.size)
        y = y.shape(1, y.size)
        
    batch_size = y.shape[0]

    return -np.sum(np.log(y[np.arrange(batch_size), t] + 1e-7)) / batch_size

In [14]:
cross_entropy_error(x_batch, t_batch)

ValueError: operands could not be broadcast together with shapes (10,10) (10,784) 

In [15]:
x_batch

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [16]:
batch_size

10

In [22]:
t = np.array([2,7,0,9,4])

In [23]:
t

array([2, 7, 0, 9, 4])

In [26]:
x_train[np.arange(5),t].shape

(5,)