In [7]:
import numpy as np

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [8]:
a = np.array([0.3, 2.9, 4.0])

y = softmax(a)

print(y)

[0.01821127 0.24519181 0.73659691]


In [9]:
a = np.array([1010, 1000, 900])
y = softmax(a)
print(y)

[9.99954602e-01 4.53978687e-05 1.68883521e-48]


In [4]:
c = np.max(a)
a - c

array([   0,  -10, -110])

In [5]:
y = softmax(a-c)

In [6]:
print(y)

[9.99954602e-01 4.53978687e-05 1.68883521e-48]
